### ISSUE TITLE
求旅客行程智能推荐系统后台服务代码

### ISSUE THREAD

**Issue by mashenghao** [DragonistYJ/BeeBeeGo#1]
兄弟，求开源后台代码

**Comment by DragonistYJ** [comment]
非常抱歉（^_^），最新版的后端代码搞丢了
现在就只有没有做优化的老版本，单纯的增删改查，就不传了

**Comment by mashenghao** [comment]
需要后台代码学习下，求大佬分享！ 邮箱 2727485259@qq.com 万分感谢
